### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by gdcfxvnjvbncvb** [ajmeese7/automatic-reactions#10]
Hi, Thank you for trying to fix, but I'm still having some problems.

```
C:\ReactDiscord>node auto
C:\ReactDiscord\node_modules\discord.js\src\client\ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read properties of undefined (reading 'id')
    at ClientDataManager.newChannel (C:\ReactDiscord\node_modules\discord.js\src\client\ClientDataManager.js:81:36)
    at Guild.setup (C:\ReactDiscord\node_modules\discord.js\src\structures\Guild.js:307:68)
    at new Guild (C:\ReactDiscord\node_modules\discord.js\src\structures\Guild.js:74:12)
    at ClientDataManager.newGuild (C:\ReactDiscord\node_modules\discord.js\src\client\ClientDataManager.js:26:19)
    at ReadyHandler.handle (C:\ReactDiscord\node_modules\discord.js\src\client\websocket\packets\handlers\Ready.js:20:91)
    at WebSocketPacketManager.handle (C:\ReactDiscord\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\ReactDiscord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\ReactDiscord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (C:\ReactDiscord\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (node:events:514:28)

Node.js v18.17.0
```

**Comment by ajmeese7** [comment]
I cannot replicate this issue, the project is working fine on my machine. I don't know why there is an error in `ClientDataManager.js`, that file doesn't exist in the [proper version](https://github.com/ajmeese7/discord.js/tree/v11) of the library that should be pulled.

What steps did you take to initialize the repository before running `node auto`?

**Comment by gdcfxvnjvbncvb** [comment]
Using Windows 11 x64
Node.js 18.17.0 and Git 2.41.0.3 installed
"git clone https://github.com/ajmeese7/automatic-reactions"
Edited "config.json" file by writing the Token and a prefix (I put the prefix "React", I don't really know what that prefix value those).
After when I enter "npm -ls" I see that discord.js isn't installed. So I enter the command "npm install discord.js@11.6.2". It gives me a warning "npm WARN deprecated discord.js@11.6.2: no longer supported" but still installs it.
Then I put node auto, and get the previous posted error

**Comment by ajmeese7** [comment]
You need to run `npm install`, doing `npm install discord.js@11.6.2` pulls from the main repository which doesn't work. I have a custom fork that I maintain for Discord API updates.

**Comment by gdcfxvnjvbncvb** [comment]
Oh. I'm a dumb dumb xD
Thank you so much for your time and pointing out what I was doing wrong.
It works perfectly. I can now spam reactions❤
